# Settings for the app
app:
  # HTML Title
  title: Active recreation spaces!
  # Header name
  name: No Sur!
  # Meta description that will show up in Google search results
  meta_description: "Which parks in Mahattan Community Board 1 need more active recreation space? Powered by Shareabouts, a mapping tool to gather crowd sourced public input."
# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat:  40.707987
      lng: -74.007232
    zoom: 17
    minZoom: 11
    maxZoom: 18
    maxBounds: [ [40.5, -74.36], [40.9, -73.47] ]
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/doittgis.NYC_DoITT_base/{z}/{x}/{y}.png
    attribution: 'Map tiles &copy; <a href="http://www.nyc.gov/doitt/">New York City DoITT</a>. Based on the latest planimetric data.'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  ATM:
    default: blue
    focused: red

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  blue:
    iconUrl: /static/css/images/marker-dollar.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
    popupAnchor:
      x: 12
      y: 6
  red:
    iconUrl: /static/css/images/marker-focused.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true

place:
  adding_supported: true
  add_button_label: Where are more active spaces needed?
  title: Identify opportunities for active spaces
  action_text: added
  anonymous_name: Someone
  submit_button_label: Submit
  items:
    - prompt: Short Description
      type: text
      name: name
      attrs:
        - key: placeholder
          value: E.g. The BofA on the corner of Canal and Broadway
    - prompt: Surcharge
      type: text
      name: surcharge
      label: 'Surcharge: $'
      attrs:
        - key: placeholder
          value: $
        - key: size
          value: 30
    - prompt: Your Name
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: Name
        - key: size
          value: 30
    - type: hidden
      name: location_type
      attrs:
        - key: value
          value: ATM

survey:
  submission_type: comments

  # Response display config
  show_responses: true
  response_name: tip
  response_plural_name: tips
  action_text: left a tip
  anonymous_name: Someone

  # Survey form config
  title: Add a Tip
  form_link_text: Add a Tip!
  submit_btn_text: Submit
  items:
    - prompt: Add a Tip
      type: textarea
      name: tip
    - prompt: Your Name
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: Support This!
  action_text: supported
  anonymous_name: Someone

pages:
  - title: About
    slug: about
    url: /static/pages/overview.html
    start_page: true
  - title: Download the Data!
    external: true
    url: /download/places.csv
