# Settings for the app
app:
  # HTML Title
  title: PHLUSH
  # Header name
  name: PHLUSH
  # Meta description that will show up in Google search results
  meta_description: _(Shareabouts is a mapping tool to gather crowd sourced public input. Use it to collect suggested locations and comments in a social, engaging process.)

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 45.5234515 
      lng: -122.6762071
    zoom: 16
    minZoom: 10
    maxZoom: 17
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  restroom-existing:
    default: restroom-existing
    focused: restroom-existing-selected
    label: _(Existing Public Restroom)
  problem:
    default: problem
    focused: problem-selected
    label: _(Problem Area)
  restroom-needed:
    default: restroom-needed
    focused: restroom-needed-selected
    label: _(Location Needing A Restroom)
  no-choice:
    default: blue
    focused: red
    label: _(No selection)

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  restroom-existing:
    #iconUrl: /static/css/images/markers/dot-e644b7.png
    iconUrl: /static/css/images/bathroom.png
    iconSize:
      width: 60
      height: 60
    iconAnchor:
      x: 30
      y: 30
  problem:
    iconUrl: /static/css/images/problem.png
    iconSize:
      width: 60
      height: 60
    iconAnchor:
      x: 30
      y: 30
  restroom-needed:
    iconUrl: /static/css/images/bathroom-wanted.png
    iconSize:
      width: 60
      height: 60
    iconAnchor:
      x: 30
      y: 30
  restroom-existing-selected:
    iconUrl: /static/css/images/bathroom-selected.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 60
      height: 60
    shadowSize:
      width: 3
      height: 41
    iconAnchor:
      x: 30
      y: 30
  problem-selected:
    iconUrl: /static/css/images/problem-selected.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 60
      height: 60
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 30
      y: 30
  restroom-needed-selected:
    iconUrl: /static/css/images/bathroom-wanted-selected.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 60
      height: 60
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 30
      y: 30
activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Contribute to the map)
  action_text: _(mapped)
  title: _(Add more information)
  action_text: _(mapped)
  anonymous_name: _(Someone)
  submit_button_label: _(Share)
  items:
# pick the type so we can filter 
    - prompt: _(Location Type)
      type: select
      name: location_type
      options:
        - label: _(Choose what to map...)
          value: no-choice
        - label: _(Existing restrooms)
          value: restroom-existing
        - label: _(Problem areas)
          value: problem
        - label: _(Restrooms needed)
          value: restroom-needed
# about existing restrooms
    - prompt: _(Restroom location information)
      type: textarea
      name: existing-restroom-location-information
      optional: true
      attrs:
        - key: placeholder
          value: _(Describe the restroom location, hours etc)
# about problem areas
    - prompt: _(Public urination)
      type: checkbox
      optional: true
      name: problem-public-urination
      attrs:
        - key: value
          value: public-urination
    - prompt: _(Public defecation)
      type: checkbox
      name: problem-public-defecation
      attrs:                
        - key: value
          value: public-defecation          
    - prompt: _(What's the problem?)
      type: textarea
      name: problem-description
      optional: true
      attrs:
        - key: placeholder
          value: _(More detail about the problem)
    - prompt: _(Upload an image of the problem)
      inputfile_label: _(Add an Image)
      type: file
      name: problem-my-image
      optional: true
      attrs:
        - key: accept
          value: image/*
# about suggestions for new restrooms
    - prompt: _(Why is this a good location for a new restroom?)
      type: textarea
      name: new-restroom-suggestion
      attrs:
        - key: placeholder
          value: _(More detail about the proposed restroom)
# general info
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support This!)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    url: /static/pages/overview.html
